/controller:
  ros__parameters:
    angular_vel_max: 0.02
    linear_vel_max: 0.03
    kp_distance: 0.08
    kp_angle: 0.05
    ki_angle: 0.0
    ke_act: 50.0
    error_threshold_dis: 0.05
    error_threshold_ang: 0.1
    angle_sensitivity: 4.0

