/controller:
  ros__parameters:
    angular_vel_max: 0.4
    linear_vel_max: 0.4
    kp_distance: 0.5
    kp_angle: 0.15
    ki_angle: -0.03
    ke_act: 50.0
    error_threshold_dis: 0.1
    error_threshold_ang: 0.3

